# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sum_system/sum_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_system || ORIG_REF_NAME==sum_system} -quiet] -quiet

# IP: bd/sum_system/ip/sum_system_processing_system7_0_0/sum_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_system_processing_system7_0_0 || ORIG_REF_NAME==sum_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/sum_system/ip/sum_system_sum_ip_0_0/sum_system_sum_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_system_sum_ip_0_0 || ORIG_REF_NAME==sum_system_sum_ip_0_0} -quiet] -quiet

# IP: bd/sum_system/ip/sum_system_ps7_0_axi_periph_0/sum_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==sum_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sum_system/ip/sum_system_rst_ps7_0_100M_0/sum_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==sum_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/sum_system/ip/sum_system_auto_pc_0/sum_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_system_auto_pc_0 || ORIG_REF_NAME==sum_system_auto_pc_0} -quiet] -quiet

# XDC: bd/sum_system/sum_system_ooc.xdc
