# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/counter_system/counter_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_system || ORIG_REF_NAME==counter_system} -quiet] -quiet

# IP: bd/counter_system/ip/counter_system_processing_system7_0_0/counter_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_system_processing_system7_0_0 || ORIG_REF_NAME==counter_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/counter_system/ip/counter_system_uart_counter_ip_0_0/counter_system_uart_counter_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_system_uart_counter_ip_0_0 || ORIG_REF_NAME==counter_system_uart_counter_ip_0_0} -quiet] -quiet

# IP: bd/counter_system/ip/counter_system_ps7_0_axi_periph_0/counter_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==counter_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/counter_system/ip/counter_system_rst_ps7_0_100M_0/counter_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==counter_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/counter_system/ip/counter_system_vio_0_0/counter_system_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_system_vio_0_0 || ORIG_REF_NAME==counter_system_vio_0_0} -quiet] -quiet

# IP: bd/counter_system/ip/counter_system_auto_pc_0/counter_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_system_auto_pc_0 || ORIG_REF_NAME==counter_system_auto_pc_0} -quiet] -quiet

# XDC: bd/counter_system/counter_system_ooc.xdc
